services:
  db:
    image: postgis/postgis:17-3.5
    container_name: cdb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: cwx
    container_name: debug
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT}/${POSTGRES_DB}
    volumes:
      - .:/code/
    ports:
      - "50000:50000"
    command:
      [
        "python",
        "-m",
        "jupyterlab",
        "--ServerApp.ip=0.0.0.0",
        "--ServerApp.port=50000",
        "--ServerApp.port_retries=0",
        "--ServerApp.open_browser=False",
      ]
    depends_on:
      db:
        condition: service_healthy

  ingest:
    image: cwx
    container_name: ingest
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT}/${POSTGRES_DB}
    volumes:
      - .:/code/
    ports:
      - "5001:5001"
    depends_on:
      db:
        condition: service_healthy
    command: ["bash", "-c", "python -u /code/src/main.py > /code/src/log.out"]

  app:
    image: cwx
    container_name: app
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT}/${POSTGRES_DB}
      PYTHONPATH: /code/src
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: ["fastapi", "run", "src/app.py", "--port", "8000"]
volumes:
  postgres_db:
